import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <nav className="absolute top-0  w-full flex justify-between  p-5 text-white z-20">
        {/* <a href="/">Logowanie</a> */}
      </nav>
      <div className="relative h-screen overflow-hidden bg-main">
        <div className="absolute inset-0 bg-black opacity-50"></div>
        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center text-white px-6">
          <h1 className="text-5xl md:text-6xl font-bold">
            Let's play together and have fun
          </h1>
          <p className="mt-4 text-xl md:text-2xl">
            Już dziś zbierz swoją drużynę, dołącz do ogłoszonego spotkania
            <br />
            bądź samemu zainicjuj chęć gry poprzez łatwą i szybką organizację
            meczu.
          </p>
          <div className="mt-8 flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-4">
            <Link
              href="/"
              className="px-6 py-3 bg-yellow-500 text-gray-900 font-bold rounded-lg hover:bg-yellow-600"
            >
              Dołącz już teraz
            </Link>
            <Link
              href="/"
              className="px-6 py-3 border border-white text-white font-bold rounded-lg hover:bg-white hover:text-gray-900"
            >
              Dowiedz się więcej
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
